version: 2.1

orbs:
    vr: kohirens/version-release@3.1.0

parameters:
    ctx_ci_cd:
        default: kohirens-automation
        description: Secrets context
        type: string
    ctx_dockerhub:
        default: kohirens-automation-dockerhub
        description: Secrets context
        type: string
    ctx_iac_test:
        default: kohirens-iac-test
        description: Secrets context
        type: string
    ssh_finger:
        description: SSH fingerprint.
        type: string
        default: "0c:23:b6:8c:c9:d0:e0:46:5e:ea:2e:39:f1:5f:7f:a4"
    triggered_flow:
        default: "workflow-selector"
        description: Workflow to be executed.
        type: string

jobs:
    run-test:
        docker:
            - image: hashicorp/terraform:1.6.3
              auth:
                  username: ${DH_USER}
                  password: ${DH_PASS}
        steps:
            - checkout
            - run:
                  command: terraform fmt -check -write=false -diff
            - run:
                  command: |
                      terraform init
                      terraform validate
                      terraform test

workflows:
    quality_checks:
        jobs:
            - run-test:
                  context:
                      - << pipeline.parameters.ctx_dockerhub >>
                      - << pipeline.parameters.ctx_iac_test >>
                  filters: { branches: { ignore: /main|auto-update-changelog/ } }

    workflow-selector:
        when:
            and:
                - equal: ["workflow-selector", << pipeline.parameters.triggered_flow >>]
                - equal: [ main, << pipeline.git.branch >> ]
        jobs:
            - vr/workflow-selector:
                  context: << pipeline.parameters.ctx_ci_cd >>
                  ssh_finger: << pipeline.parameters.ssh_finger >>

    publish-changelog:
        when:
            and:
                - equal: ["publish-changelog", << pipeline.parameters.triggered_flow >>]
        jobs:
            - vr/publish-changelog:
                  context: << pipeline.parameters.ctx_ci_cd >>
                  ssh_finger: << pipeline.parameters.ssh_finger >>

    publish-release-tag:
        when:
            and:
                - equal: ["publish-release-tag", << pipeline.parameters.triggered_flow >>]
        jobs:
            - vr/tag-and-release:
                  context: << pipeline.parameters.ctx_ci_cd >>
