style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: 'https://github.com/kohirens/aws-tf-s3-backend.git'
options:
  commits:
    filters:
      Type:
        - add
        - atm
        - chg
        - ci
        - dep
        - doc
        - fix
        - mnt
        - rft
        - rmv
  commit_groups:
    title_maps:
      add: Added
      atm: Automated
      chg: Changed
      ci: Continuous Integration
      dep: Deprecated
      doc: Documented
      fix: Fixed
      mnt: Maintained
      rft: Refactored
      rmv: Removed
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
